name: links

services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:release
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATA_DIR=/data
    volumes:
      - ${KARAKEEP_DATA_PATH}:/data
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared-self-host