name: books

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    ports:
      - 8083:8083
    volumes:
      - ${BOOKS_PATH}:/books
      - ${CALIBRE_WEB_CONFIG_PATH}:/config
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared-self-host