ingress:
  - hostname: jellyfin.mjjmedia.com
    service: http://caddy:80
  - hostname: audiobooks.mjjmedia.com
    service: http://caddy:80
  - hostname: music.mjjmedia.com
    service: http://caddy:80
  - hostname: comics.mjjmedia.com
    service: http://caddy:80
  - hostname: books.mjjmedia.com
    service: http://caddy:80
  - service: http_status:404