name: comics

services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    ports:
      - 25600:25600
    environment:
      - SERVER_PORT=25600
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=@supplements
    volumes:
      - ${COMICS_PATH}:/comics:ro
      - ${MAGAZINES_PATH}:/magazines:ro
      - ${KOMGA_CONFIG_PATH}:/config
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared-self-host