name: proxy

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    networks:
      - shared

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --config
      - /etc/cloudflared/config.yml
      - run
      - --credentials-file
      - /etc/cloudflared/${CLOUDFLARED_CREDENTIALS_FILENAME}
      - ${CLOUDFLARED_TUNNEL_ID}
    volumes:
      - ./cloudflared-config.yml:/etc/cloudflared/config.yml:ro
      - ~/.cloudflared/${CLOUDFLARED_CREDENTIALS_FILENAME}:/etc/cloudflared/${CLOUDFLARED_CREDENTIALS_FILENAME}:ro
    networks:
      - shared
    depends_on:
      - caddy

volumes:
  caddy-config:
    external: true
  caddy-data:
    external: true

networks:
  shared:
    name: shared-self-host
    external: true