name: audiobooks

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - 13378:80
    volumes:
      - ${AUDIOBOOKS_PATH}:/audiobooks:ro
      - ${ABS_CONFIG_PATH}:/config
      - ${ABS_METADATA_PATH}:/metadata
    networks:
      - shared

networks:
  shared:
    name: shared-self-host
    external: true
